### ISSUE TITLE
A crash on superuser branch

### ISSUE THREAD

**Issue by YISAMULIN** [takusan23/NewRadioSupporter#5]
いつもソースコードを拝見させていただき、ありがとうございます。
superuser branchにてPhysicalChannelConfigの情報を取得してみていますが、
下記ようなエラーが出ており、解決策などがありましたら、ぜひ提示していただきたいです。

試験端末:
- A103SO(Android12) 非Root
- Shizukuアプリのインストール(承認済み)済み。

```
java.lang.NoSuchMethodError: No interface method listenWithEventList(ZZILjava/lang/String;Ljava/lang/String;Lcom/android/internal/telephony/IPhoneStateListener;[IZ)V in class Lcom/android/internal/telephony/ITelephonyRegistry; or its super classes (declaration of 'com.android.internal.telephony.ITelephonyRegistry' appears in /system/framework/framework.jar!classes4.dex)
at io.github.takusan23.newradiosupporter.tool.ShizukuTool$collectPhysicalChannelConfigList$1.invokeSuspend(ShizukuTool.kt:145)
at io.github.takusan23.newradiosupporter.tool.ShizukuTool$collectPhysicalChannelConfigList$1.invoke(Unknown Source:8)
at io.github.takusan23.newradiosupporter.tool.ShizukuTool$collectPhysicalChannelConfigList$1.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:322)
at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Unknown Source:0)
at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo(Builders.kt:336)
at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Suppressed: java.lang.NoSuchMethodError: No interface method listenWithEventList(ZZILjava/lang/String;Ljava/lang/String;Lcom/android/internal/telephony/IPhoneStateListener;[IZ)V in class Lcom/android/internal/telephony/ITelephonyRegistry; or its super classes (declaration of 'com.android.internal.telephony.ITelephonyRegistry' appears in /system/framework/framework.jar!classes4.dex)
	at io.github.takusan23.newradiosupporter.tool.ShizukuTool$collectCellInfoList$1.invokeSuspend(ShizukuTool.kt:189)
	at io.github.takusan23.newradiosupporter.tool.ShizukuTool$collectCellInfoList$1.invoke(Unknown Source:8)
	at io.github.takusan23.newradiosupporter.tool.ShizukuTool$collectCellInfoList$1.invoke(Unknown Source:4)
	... 17 more
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@44b6adb, androidx.compose.runtime.BroadcastFrameClock@f0d6978, StandaloneCoroutine{Cancelling}@9a8a851, AndroidUiDispatcher@fbe88b6]
2023-06-06 19:44:12.398 10810-10810 Process       
```

**Comment by takusan23** [comment]
おつかれさまです。
手元の Android 12系 端末でも同様のエラーが出ることを確認しました。
調べた結果、メソッドの引数が Android 13 と 12 で違う事が原因だったみたいです。
Android 12 でも動くように修正し push しましたので、pull して再度ビルドを試してみてください・・・！

よろしくお願いします 🙏

**Comment by YISAMULIN** [comment]
改修したリソースでエラーがなく、アプリが起動されています！
迅速に対応していただき、大変助かりました。
